feat: navigation item from other locale copy [CU-2dzbdxg]
VirtusLab-Open-Source/strapi-plugin-navigation pull request #216
Opened 2022-05-14 15:15 UTC by CodeVoyager

## Ticket

https://app.clickup.com/t/2dzbdxg

depends on: https://github.com/VirtusLab-Open-Source/strapi-typed/pull/9

## Summary

- copying details of a navigation item from locale to locale
- minor ui performance tweaks

![image](https://user-images.githubusercontent.com/13495487/168433286-60aea341-da7b-4673-b8e3-537534bc71f4.png)

## Test Plan

- if locale is not selected in "Copy details from", "copy" button is inactive
- if locale is selected in "Copy details from", "copy" button is active
- if in source locale version there is matching node in navigation tree it will be applied to currently edited navigation item
- if found item's related content has localised version it will be used
- if found item's related content does not have localised version or content is not localised whatsoever, item will be applied "as-is"
- if matching node was not found a message will be displayed as select's error message
- if generic request error will happed a message will be displayed as select's error message
- generic and not found messages are different

2022-05-14 15:15 UTC, cyp3rius commented
Task linked: [CU-2dzbdxg Copying navigation items between locales](https://app.clickup.com/t/2dzbdxg)

2022-05-18 09:31 UTC, ltsNotMike requested changes

2022-05-18 09:31 UTC, ltsNotMike commented on admin/src/pages/View/components/NavigationItemForm/index.js
> +  const [isLoading, setIsLoading] = useState(isLoading);
```suggestion
  const [isLoading, setIsLoading] = useState(isPreloading);
```

_Uncaught ReferenceError: Cannot access 'isLoading' before initialization_

2022-05-19 16:54 UTC, CodeVoyager commented on admin/src/pages/View/components/NavigationItemForm/index.js
> +  const [isLoading, setIsLoading] = useState(isLoading);
Updated

2022-05-19 20:27 UTC, ltsNotMike approved these changes

2022-05-30 07:15 UTC, cyp3rius approved these changes

2022-05-30 07:16 UTC, cyp3rius commented
@CodeVoyager resolve conflict please and it's ready to be merged.

2022-05-30 14:53 UTC, CodeVoyager commented
Issues are resolved @cyp3rius

2022-06-03 08:41 UTC, merged