feat: navigation meta data
VirtusLab-Open-Source/strapi-plugin-navigation pull request #376
Opened 2023-09-14 13:08 UTC by CodeVoyager

## Ticket

https://github.com/VirtusLab/strapi-plugin-navigation/issues/370

## Summary

- id and slug of navigation displayed in header

![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/13495487/a590fb16-2d67-41ee-8a26-537032660282)

## Test Plan

- build admin resource
- display navigation details page
- result should be similar to example
- validate displayed `id` and `slug` against details in dev tools' `Network` tab

2023-09-15 05:45 UTC, cyp3rius approved these changes

2023-09-15 05:45 UTC, cyp3rius requested changes

2023-09-15 05:45 UTC, cyp3rius commented on admin/src/pages/View/components/NavigationHeader/index.js
> +
Remove please

2023-09-15 18:07 UTC, CodeVoyager commented on admin/src/pages/View/components/NavigationHeader/index.js
> +
Cleaned

2023-09-18 11:00 UTC, cyp3rius approved these changes

2023-09-19 07:56 UTC, merged