Add option to render selected child of root nav
VirtusLab-Open-Source/strapi-plugin-navigation pull request #77
Opened 2021-06-02 12:06 UTC by mateutek

## Ticket

https://github.com/VirtusLab/strapi-plugin-navigation/issues/76
## Summary

What does this PR do/solve? 

Added an option to filter out the children by the `uiRouterKey` for all of the types.

There is an option to distinguish between id/slug for the flat type to use strapi filtration.

## Test Plan

How are you testing the work you're submitting?

2021-06-03 17:08 UTC, cyp3rius approved these changes

2021-06-03 17:09 UTC, cyp3rius commented
@Kronos66 may I ask you for review from your end also?

2021-06-04 05:18 UTC, Kronos66 requested changes

2021-06-04 05:18 UTC, Kronos66 commented on controllers/navigation.js
> +    const {id} = parseParams(params);
Could you revert this formatting? We should avoid formatting changes

2021-06-04 05:18 UTC, Kronos66 commented on controllers/navigation.js
> +    const {idOrSlug} = parseParams(params);
as above, please revert formatting changes

2021-06-04 05:18 UTC, Kronos66 commented on controllers/navigation.js
> +    const {body = {}} = ctx.request;
as above, please revert formatting changes

2021-06-04 05:18 UTC, Kronos66 commented on controllers/navigation.js
> +    const {body = {}} = ctx.request;
as above, please revert formatting changes

2021-06-04 05:18 UTC, Kronos66 commented on services/navigation.js
> +          _sort: "order:asc",
please revert these changes, we prefer single quote

2021-06-04 05:18 UTC, Kronos66 commented on services/navigation.js
> +
only these changes in this method are new, the rest looks like a problem with code formatting, could you revert this?

2021-06-04 05:20 UTC, Kronos66 commented
Hi, generally look good but in this PR you added a lot of changes related to formatting code. Please revert these changes and we can progress this PR :).

CC: @cyp3rius  Could we add something formatter I didn't see something like prettier or eslint config

2021-06-04 07:01 UTC, mateutek commented
Hey, 
It was auto-formatting based on config from IDE

2021-06-04 07:08 UTC, Kronos66 approved these changes

2021-06-04 07:09 UTC, merged

2021-06-04 07:10 UTC, cyp3rius commented
Thanks @mateutek, I will provide default prettier config also to avoid format changes :) Your change is going to be part of next release.